### ISSUE TITLE
List of functions

### ISSUE THREAD

**Issue by Oleg-Lopes** [chas-academy/13-beta-product-release-gold#7]

**Comment by eleninikou** [comment]
FU1  Beställa tjänst
		Kunden skall kunna:
FU 1.1	 Välja typ av tjänst med fritext
	FU 1.2  Välja när den ska åtgärdas med time-picker + date-picker
FU 1.3  Beskriva typ av ärende i form av fritext
	FU 1.4  Kunna bifoga foto
	FU 1.5  Fylla i kontaktpersonens namn och telefonnummer
FU 1.6  Fylla i adress

FU2  Skapa reklamation
	Kunden skall kunna:
	FU 2.1  Välja ärendenummer reklamationen kopplas till
	FU 2.2  Välja när reklamationen skall åtgärdas med time-picker / + 
             date-picker.
	FU 2.3  Beskriva ärendet i form av fritext
FU 2.4  Kunna bifoga foto
FU 2.5  Fylla i kontaktpersonens namn och telefonnummer

FU3  Motta bekräftelse
	Kunden skall kunna:
	FU 3.1  Få en bekräftelse när en beställning har mottagits och behandlats
	FU 3.2  Få en bekräftelse när arbetet är slutfört

FU4  Ärendehistorik
	Kunden skall kunna:
FU 4.1  Se sin ärendehistorik  
( FU 4.2  Avbryta en aktiv beställning )
Admin skall kunna:
FU 4.3  Se ärendehistorik för hanterade ärenden

FU5  Hantering av ärenden/Admin
	Admin skall kunna
	FU 5.1  Motta beställningar, reklamationer och avvikelser
	FU 5.2  Välja att skicka vidare ärende till anställd
FU 5.3  Lägga till relevant information till ärendet och redigera det
FU 5.4  Ta bort inkommet ärende
FU 5.5  Få bekräftelse på att Anställd utfört arbete
FU 5.6  Lägga till/Skapa konto för sina anställda
FU 5.7  Se en lista över sina anställda
FU 5.8  Registrera konto för befintliga kunder

FU6  Ta emot ärende
	Anställd skall kunna
	FU 6.1  Ta emot ärende
	FU 6.2  Bifoga foto på utfört arbete
	FU 6.3  Bekräfta att arbetet är slutfört

FU7  Registrering/Inloggning
	Kund skall kunna
	FU 7.1  Registrera ett konto
	FU 7.2  Uppdatera sin information
	FU 7.3  Radera konto
	Kund, Anställd och admin skall kunna
	FU 7.4  Logga in
Vid mån av tid: 

FU8  Betygsätta service
	Kunden skall kunna:
FU 8.1 Betygsätta hantering av ärende
	FU 8.2 Skriva en recension kopplad till ärendet
